import test from 'node:test';
import { readFile } from 'node:fs/promises';
import { geometryForSolid, viewFrame } from '../docs/projection-core.js';
import { analyzeProjectionStructure } from '../docs/projection-geometry-analysis.js';

const projections=JSON.parse(await readFile(new URL('../docs/data/projections.json',import.meta.url),'utf8'));
const views=JSON.parse(await readFile(new URL('../docs/data/projection-views.json',import.meta.url),'utf8'));
const focus=new Map([['정육면체',new Set(['재배치'])],['정팔면체',new Set(['분배'])],['정십이면체',new Set(['교환','연쇄','관계 전달','다중 종속','관계망','연결','중첩 결속','재배선'])],['정이십면체',new Set(['치환','확정','유예','선택 유보','재선택','재합류'])]]);
const norm=a=>{a%=Math.PI;if(a<0)a+=Math.PI;return a}; const ad=(a,b)=>{const d=Math.abs(norm(a)-norm(b));return Math.min(d,Math.PI-d)};
function reflect(a,[x,y]){const c=Math.cos(2*a),s=Math.sin(2*a);return[x*c+y*s,x*s-y*c]}
function axes(nodes,indices,scale,tolf=.006){const cand=[];const add=a=>{a=norm(a);if(!cand.some(x=>ad(x,a)<1e-5))cand.push(a)};for(let p=0;p<indices.length;p++){const i=indices[p],ai=Math.atan2(nodes[i].xy[1],nodes[i].xy[0]);add(ai);for(let q=p+1;q<indices.length;q++){const j=indices[q],aj=Math.atan2(nodes[j].xy[1],nodes[j].xy[0]);const b=Math.atan2(Math.sin(ai+aj),Math.cos(ai+aj))/2;add(b);add(b+Math.PI/2)}}const ok=[];for(const a of cand){const used=new Set();let valid=true;for(const i of indices){const t=reflect(a,nodes[i].xy);let bj=-1,bd=Infinity;for(const j of indices){if(used.has(j))continue;const d=Math.hypot(nodes[j].xy[0]-t[0],nodes[j].xy[1]-t[1]);if(d<bd){bd=d;bj=j}}if(bj<0||bd>scale*tolf){valid=false;break}used.add(bj)}if(valid)ok.push(a)}const out=[];for(const a of ok.sort((a,b)=>a-b))if(!out.some(x=>ad(x,a)<Math.PI/180))out.push(a);return out.map(a=>Number((a*180/Math.PI).toFixed(2)))}
test('outer hull symmetry',()=>{for(const solid of projections.solids){const wanted=focus.get(solid.name);if(!wanted)continue;const vs=views.solids.find(v=>v.name===solid.name),g=geometryForSolid(solid.name);for(const item of solid.classes){if(!wanted.has(item.role.name))continue;const v=vs.views.find(x=>x.classId===item.id),s=analyzeProjectionStructure(g.vertices,g.edges,viewFrame(v.viewDirection,v.rollDegrees));const scale=Math.max(1,...s.nodes.map(n=>Math.hypot(...n.xy)));console.log(JSON.stringify({name:`${solid.name}-${item.role.name}`,outer:axes(s.nodes,s.layers.at(-1),scale),outer2:axes(s.nodes,s.layers.at(-1),scale,.02)}))}}});
